---
title: "Venäläisten suhtautuminen Ukrainan sotaan"
author: "Eemil Mitikka"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Ohjelmakirjastot

```{r}
library(tidyverse)
library(haven)
# library(here)
# library(rdhs)
library(labelled)
library(survey)
library(extrafont)
library(magick)
library(rnaturalearth)
library(rvest)
library(lubridate)
# library(ggrepel)
# library(countrycode)
# library(ggthemes)
# install.packages("sf")
```


# Visualisointiteemat ja funktiot

```{r}
# Määrittele teema graafeille
theme_meduza <- function() {
  font <- "Georgia" # assign font family up front
  theme_minimal() %+replace% # replace elements we want to change
    
    theme(
      # Plot background color
      plot.background = element_rect(fill = "#EEEDE4"), # background color
      # Plot grids color
      panel.grid.major = element_line(colour = "#CCCDC4"),
      panel.grid.minor = element_line(colour = "#CCCDC4"),
      # Text elements
      plot.title = element_text(
        family = font,
        size = 18,
        face = 'bold',
        hjust = 0,
        vjust = 2,
        margin = margin(15,0,0,0)),
      
      plot.subtitle = element_text( # title
                   family = font, # set font family
                   face = 'bold', # bold typeface
                   size = 14), # size of the title
      # Plot caption
      plot.caption = element_text(
        family = font,
        size = 10,
        face = 'bold',
        hjust = 1,
        colour = "#61605A"),
      # Axis title
      axis.title = element_text(
        family = font,
        size = 12),
      
      axis.text = element_text(
        family = font,
        face = 'bold',
        size = 12),
      
      axis.text.x = element_text(
        margin = margin(5, b = 10)),
      
      # Legend elements
      legend.title = element_text(
        family = font,
        size = 10,
        face = "bold"),
      legend.text = element_text(
        family = font,
        size = 8,
        face = "bold")
    )
}

# Määrittele graafeihin kuvatekstit
## VTsIOM
caption_vtsiom <- function() {
  labs(
  caption = "Lähde: VTsIOM (25.2.–27.2.2022)
  N = 3200
  Kuva: Eemil Mitikka"
  )
}

## Riippumaton tutkijaryhmä
caption_riipp <- function() {
  labs(
    caption = "Lähde: Riippumaton tutkijaryhmä (28.2.–1.3.2022)
    N = 1640
    Kuva: Eemil Mitikka"
  )
}

# Levada ja VTsIOM rankingit
caption_ranking <- function() {
  labs(
    caption = "Lähde: Levada-keskus (elokuu 1999–maaliskuu 2022), VTsIOM (15.1.2006–20.3.2022)
    Kuva: Eemil Mitikka"
  )
}

# Russian Field
caption_rf <- function() {
  labs(
    caption = "Lähde: Russian Field (26–28.2.2022)
    N=2000
    Kuva: Eemil Mitikka"
  )
}


# Määrittele värit graafeihin
harmaa <- "#9E9E9E" # "En osaa sanoa"
punainen <- "#D37463" # "Ennemmin en tue"
vihrea <- "#63AEA6" # "Ennemmin tuen"

# Tuo Aleksanteri-instituutti logo visualisointeihin
img_filepath <- paste(here::here("kuvat/"))
ai_logo_tiedosto <- paste(img_filepath, "ai_logo_uusi_tausta.svg", sep = "")
logo_ai <- image_read(ai_logo_tiedosto)
## Määrittele AI-logo funktio
ai_logo <- function() {
  grid::grid.raster(
    logo_ai,
    x = 0.02,
    y = 0.03,
    just = c("left", "bottom"), width = unit(0.5, "inches")
  )
}

# Määrittele prosentit funktio
prosentit <- function() {
  geom_text(aes(
  label = scales::percent(prosentti, accuracy = 1), vjust = -.5),
          size = 4, 
          fontface = "bold",
          family = "Georgia")
}

# Määrittele "kuvat" kansion tallennuspolku
kuvat <- paste(here::here("kuvat/"))


```


# Datan tuonti ja putsaus

```{r}
# Määrittele työhakemisto "data" kansioon
data_filepath <- paste(here::here("data/"))

# Määrittele tiedostonimet tuotavalle datalle
vtsiom_25.2.tiedosto <- paste(data_filepath, "База_Спецоперация (25.02).sav", sep = "")
vtsiom_27.2.tiedosto <- paste(data_filepath, "База_Спецоперация (27.02).sav", sep = "")
riipp_data_tiedosto <- paste(data_filepath, "survey_fin_with_coded_open.sav", sep = "")

# Tuo data
vtsiom_25.2. <- read_spss(vtsiom_25.2.tiedosto)
vtsiom_27.2. <- read_spss(vtsiom_27.2.tiedosto)
riipp_data <- read_spss(riipp_data_tiedosto)

# Yhdistä VTsIOM data
sota_molemmat <- merge(vtsiom_25.2., vtsiom_27.2., all = TRUE)

# Suomenna muuttujat
sota_molemmat <- sota_molemmat %>% 
  mutate(vastaaja_tunnus = ID,
         sukupuoli = SEX,
         ika = AGE,
         koulutus = EDU,
         federaatio_piiri = FO,
         asuinalue_koko = TIP,
         sota_hyvaksynta = vo4,
         sota_paamaara = vo5,
         tv_katselu = TV,
         internet_kaytto = d1,
         talous_perhe = DOHOD_0,
         tyotilanne = PROF1,
         tyo_organisaatio = PROF2,
         tyopaikka_sektori = PROF3,
         otanta_paino = weight1
  )

# Suomenna muuttujien arvot
sota_molemmat <- sota_molemmat %>% 
  mutate(sukupuoli = recode(sukupuoli, '1' = 'Mies', '2' = 'Nainen'),
         koulutus = recode(koulutus, 
                           '1' = 'Peruskoulu', 
                           '2' = 'Kesken oleva keskiasteen koulutus',
                           '3' = 'Keskiasteen koulutus (lukio tai ammattikoulu)',
                           '4' = 'Keskiasteen erityiskoulutus (teknikum, college)',
                           '5' = 'Kesken oleva korkeakoulu (4-vuosikurssi tai ylempi), korkeakoulu',
                           '6' = 'Kaksi tai useampi korkeakoulututkintoa, akateeminen tutkinto'),
         federaatio_piiri = recode(federaatio_piiri, 
                                   '1' = 'Keskinen federaatiopiiri', 
                                   '2' = 'Luoteinen federaatiopiiri',
                                   '3' = 'Eteläinen federaatiopiiri',
                                   '4' = 'Pohjois-Kaukasian federaatiopiiri',
                                   '5' = 'Volgan federaatiopiiri',
                                   '6' = 'Uralin federaatiopiiri',
                                   '7' = 'Siperian federaatiopiiri',
                                   '8' = 'Kaukoidän federaatiopiiri'),
         asuinalue_koko = recode(asuinalue_koko, 
                                 '1' = 'Miljoonakaupunki',
                                 '2' = '500,000-950,000 asukkaan kaupunki',
                                 '3' = '100,000-500,000 asukkaan kaupunki',
                                 '4' = '50,000-100,000 asukkaan kaupunki',
                                 '5' = 'Alle 50,000 asukkaan kaupunki',
                                 '6' = 'Kaupungin tapainen taajama',
                                 '7' = 'Kylä'),
         sota_hyvaksynta = recode(sota_hyvaksynta,
                                  '1' = 'Ennemmin tuen',
                                  '2' = 'Ennemmin en tue',
                                  '99' = 'En osaa sanoa'),
         sota_paamaara = recode(sota_paamaara,
                                '1' = 'Suojella Donetskin ja Luhanskin kansantasavaltojen venäjänkielistä väestöä',
                                '2' = 'Demilitarisoida Ukraina, turvata Venäjän rajat',
                                '3' = 'Estää NATOn sotilastukikohtien sijoittaminen Ukrainaan',
                                '4' = 'Jakaa Ukraina ja vakiinnuttaa Venäjän vaikutus Ukrainaan',
                                '5' = 'Vaihtaa Venäjälle epäystävällinen poliittinen hallinto',
                                '6' = 'Muuttaa Ukrainan poliittista kurssia, denatsifikoida Ukraina',
                                '98' = 'Muu (kuvailkaa)',
                                '99' = 'En osaa sanoa'),
         tv_katselu = recode(tv_katselu,
                             '1' = 'Katson yli neljä tuntia päivittäin',
                             '2' = 'Katson alle neljä tuntia päivittäin',
                             '3' = 'Muutaman kerran viikossa',
                             '4' = 'Muutaman kerran kuukaudessa',
                             '5' = 'Harvoin, mutta useammin kuin kerran puolessa vuodessa',
                             '6' = 'En katso televisiota'),
         internet_kaytto = recode(internet_kaytto,
                                  '1' = 'Käytän internettiä yli neljä tuntia päivässä',
                                  '2' = 'Käytän internettiä päivittäin, mutta alle neljä tuntia päivässä',
                                  '3' = 'Käytän internettiä kerran viikossa',
                                  '4' = 'Käytän internettiä kerran kuukaudessa',
                                  '5' = 'Käytän harvoin internettiä, mutta useammin kuin kerran puolessa vuodessa',
                                  '96' = 'En käytä internettiä'),
         talous_perhe = recode(talous_perhe,
                               '1' = 'Erittäin hyvä taloudellinen tilanne',
                               '2' = 'Hyvä taloudellinen tilanne',
                               '3' = 'Keskimääräinen taloudellinen tilanne',
                               '4' = 'Huono taloudellinen tilanne',
                               '5' = 'Erittäin huono taloudellinen tilanne',
                               '99' = 'En osaa sanoa'),
         tyotilanne = recode(tyotilanne,
                             '1' = 'Työtön eläkeläinen (ml. työkyvyttömyyseläke)',
                             '2' = 'Työssä käyvä eläkeläinen',
                             '3' = 'Työtön opiskelija',
                             '4' = 'Työssäkäyvä opiskelija',
                             '5' = 'Väliaikaisesti työtön, työtön',
                             '6' = 'Vanhempainvapaalla, hoitovapaalla',
                             '7' = 'Palkkatyöläinen',
                             '8' = 'Yrittäjä, yrityksenomistaja',
                             '9' = 'Itsensätyöllistäjä',
                             '99' = 'En osaa sanoa',
                             '999' = 'Kieltäytyy vastaamasta'),
         tyo_organisaatio = recode(tyo_organisaatio,
                                   '1' = 'Yksityinen voittoa tavoitteleva organisaatio',
                                   '2' = 'Julkinen ja maksuttomia palveluita tarjoava organisaatio',
                                   '3' = 'Voittoa tavoittelematon yleishyödyllinen järjestö',
                                   '4' = 'Valtajärjestelmät, hallinto, oikeusjärjestelmä',
                                   '5' = 'Järjestysvalta, asevoimat, Venäjän hätätilaministeriö',
                                   '99' = 'Ei osaa sanoa/kieltäytyy vastaamasta'),
         tyopaikka_sektori = recode(tyopaikka_sektori,
                                    '1' = 'Teollisuus, tuotanto',
                                    '2' = 'Maatalous, metsäteollisuus, metsästys, kalastus, kalanviljely',
                                    '3' = 'Rakentaminen',
                                    '4' = 'Asunto- ja kunnallistalous',
                                    '5' = 'Koulutus, tiede',
                                    '6' = 'Terveydenhuolto',
                                    '7' = 'Sosiaalipalvelut, sosiaaliturva',
                                    '8' = 'Kulttuuri, taide, urheilu',
                                    '9' = 'Vapaa-aika, viihdeteollisuus, turismi',
                                    '10' = 'Kaupungin- ja kunnallishallinto',
                                    '11' = 'Järjestysvalta, valtarakenteet, hätätilaministeriö, asepalvelus',
                                    '12' = 'Media/tiedotusvälineet',
                                    '13' = 'Informaatioteknologia, tietoliikenne, Internet',
                                    '14' = 'Kauppa (tukku-, jälleenmyynti-, verkko- ja kiinteistökauppa)',
                                    '15' = 'Finanssi- ja vakuutustoiminta, pankkipalvelut',
                                    '16' = 'Kuljetus ja varastointi (materiaalitalous)',
                                    '17' = 'Ravitsemispalvelut, ravintola- ja matkailuliiketoiiminta',
                                    '18' = 'Palvelu ja huolto, kuluttajapalvelut',
                                    '98' = 'Muu, mikä?',
                                    '99' = 'Ei osaa sanoa', 
                                    '999' = 'Kieltäytyy vastaamasta'
                                    )
         )




# Tee muunna kategoriset muuttujat tekstimuuttujista kategorisiksi
nimet <- colnames(sota_molemmat[19:29])
sota_molemmat[,nimet] <- lapply(sota_molemmat[,nimet], factor)
```

# Datan visualisoinnit

## VTsIOMin data

```{r}
# Määrittele värit 
harmaa <- "#9E9E9E" # "En osaa sanoa"
punainen <- "#D37463" # "Ennemmin en tue"
vihrea <- "#63AEA6" # "Ennemmin tuen"

# Sodan tuki molempien datojen valossa
png(paste(kuvat, "vtsiom_sodan_kannatus.png", sep = ""), width = 961, height = 777)
sota_molemmat %>% 
  group_by(sota_hyvaksynta) %>% 
  summarise(n = n()) %>% 
  mutate(prosentti = n / sum(n)) %>% 
  ggplot(aes(x = sota_hyvaksynta, y = prosentti, fill = sota_hyvaksynta)) +
  geom_col() +
  scale_fill_manual(values = c(harmaa, punainen, vihrea)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), breaks = seq(.2, .6, .1)) +
  labs(title = 'VTsIOM: tuetteko "sotaoperaatiota"?',
       fill = '"Sotaoperaation"\ntukeminen',
       y = NULL,
       x = NULL) +
  guides(fill = FALSE) + # remove legend
  prosentit() +
  caption_vtsiom() +
  theme_meduza() +
  theme(axis.text.x = element_text(colour = c(harmaa, punainen, vihrea)))
dev.off()
## Tallennettu spekseillä Width: 961 ja Heigth 777, tiedostonimi: vtsiom_sodan_kannatus.png

# Laske ikäryhmäkohtainen sodan kannatus
sota_tuki_vs_ika <- sota_molemmat %>% 
  select(ika, sota_hyvaksynta) %>% 
  group_by(ika, sota_hyvaksynta) %>% 
  summarise(n = n()) %>% 
  mutate(prosentti_ika = n / sum(n)) %>% 
  ungroup()

# VTsIOM: iän yhteys sodan kannatukseen
png(paste(kuvat, "vtsiom_ika_vs_kannatus.png", sep = ""), width = 1068, height = 841, res = 85)
sota_tuki_vs_ika %>% 
  filter(ika <= 75) %>% 
  ggplot(aes(x = ika, y = prosentti_ika, group = sota_hyvaksynta)) +
  # geom_point(color = punainen) +
  geom_smooth(aes(color = sota_hyvaksynta), se = F) +
  scale_x_continuous(breaks = seq(20, 70, 10)) +
  theme_meduza() +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), breaks = seq(.1, .8, .1)) +
  scale_color_manual(values = c("black", "#D37463", vihrea)) +
  labs(title = 'VTsIOM: iän yhteys "sotaoperaation" kannatukseen (trendiviivat)',
       y = 'Prosenttia ikäluokasta (%)',
       x = "Vastaajan ikä vuosina",
       color = "Sodan hyväksyntä") +
  guides(color = guide_legend(reverse=TRUE)) +
  caption_vtsiom()
ai_logo()
dev.off()
## Tallennettu spekseillä Width 1068 ja Heigth 841, tiedostonimi "vtsiom_ika_vs_kannatus.png"

# VTSIOM: laske sodan kannatus sukupuolen mukaan
sota_tuki_vs_sukupuoli <- sota_molemmat %>% 
  select(sukupuoli, sota_hyvaksynta, ika) %>% 
  group_by(sukupuoli, ika, sota_hyvaksynta) %>%
  summarise(n = n()) %>% 
  mutate(prosentti_ika = n / sum(n)) %>% 
  ungroup()

# VTSIOM: sodan kannatus iän ja sukupuolen mukaan  
png(paste(kuvat, "vtsiom_ika_sukupuoli.png", sep = ""), width = 1068, height = 841, res = 85)
sota_tuki_vs_sukupuoli %>% 
  filter(ika <= 75) %>% 
  filter(sota_hyvaksynta == "Ennemmin en tue") %>% 
  ggplot(aes(x = ika, y = prosentti_ika, group = sukupuoli)) +
  geom_smooth(aes(color = sukupuoli), se = F) +
  scale_x_continuous(breaks = seq(20, 70, 10)) +
  theme_meduza() +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), breaks = seq(.1, .7, .1)) +
  guides(color = guide_legend(reverse=TRUE)) +
  scale_color_manual(values = c("black", vihrea)) +
  labs(title = 'VTsIOM: sukupuolen ja iän yhteys "sotaoperaation" kannatukseen (trendiviivat)',
       y = 'Prosenttia miehistä ja naisista ikäluokittain (%)',
       x = "Vastaajan ikä vuosina",
       color = '"Ennemmin vastustan"\nsukupuolittain') +
  caption_vtsiom()
ai_logo()
dev.off()
## Tallennettu spekseillä Width 1068 ja Heigth 841, tiedostonimi: vtsiom_ika_sukupuoli.png

# Luo ikäluokat, TV-katselu, netin käyttö, kaupunkiluokat ja koulutusluokat muuttujat
sota_molemmat <- sota_molemmat %>% 
  mutate(ikaluokat =
             case_when(ika >= 18 & ika <= 30 ~ "18–30-vuotiaat",
                     ika >= 31 & ika <= 45 ~ "31–45-vuotiaat",
                     ika >= 46 & ika <= 60 ~ "46–60-vuotiaat",
                     ika > 60 ~ "Yli 60-vuotiaat")) %>%
  mutate(tv_luokat =
           case_when(
             tv_katselu %in% c("Katson yli neljä tuntia päivittäin", "Katson alle neljä tuntia päivittäin") ~ "Katson päivittäin televisiota", 
             tv_katselu %in% c("En katso televisiota", "Muutaman kerran viikossa", "Harvoin, mutta useammin kuin kerran puolessa vuodessa", "Muutaman kerran kuukaudessa") ~ "En katso päivittäin televisiota")) %>% 
  mutate(netti_luokat =
           case_when(
             	internet_kaytto %in% c("Käytän internettiä yli neljä tuntia päivässä", "Käytän internettiä päivittäin, mutta alle neljä tuntia päivässä") ~ "Käytän päivittäin internettiä",
             	internet_kaytto %in% c("En käytä internettiä", "Käytän internettiä kerran kuukaudessa", "Käytän internettiä kerran viikossa", "Käytän harvoin internettiä, mutta useammin kuin kerran puolessa vuodessa") ~ "En käytä päivittäin internettiä")) %>% 
  mutate(kaupunkiluokat =
             case_when(asuinalue_koko == "Miljoonakaupunki" ~ "Miljoonakaupungit",
                     asuinalue_koko %in% c("100,000-500,000 asukkaan kaupunki", "500,000-950,000 asukkaan kaupunki")  ~ "Suuret kaupungit",
                     asuinalue_koko == "50,000-100,000 asukkaan kaupunki" ~ "Keskikokoiset kaupungit",
                     asuinalue_koko %in% c("Alle 50,000 asukkaan kaupunki", "Kaupungin tapainen taajama", "Kylä") ~ "Pienet kaupungit ja kylät")
         ) %>% 
  mutate(koulutusluokat =
           case_when(koulutus %in% c("Kesken oleva korkeakoulu (4-vuosikurssi tai ylempi), korkeakoulu", "Kaksi tai useampi korkeakoulututkintoa, akateeminen tutkinto") ~ "Korkeakoulututkinto",
                     TRUE ~ "Ei korkeakoulututkintoa"))

# VTSIOM: Netti ja tuki
vtsiom_netti_ja_tuki <- sota_molemmat %>% 
  group_by(ikaluokat, netti_luokat, sota_hyvaksynta) %>% 
  summarise(n = n()) %>% 
  mutate(prosentti = n / sum(n))

# VTSIOM: Visualisoi sodan kannatus ikäluokan ja netin kulutuksen mukaan
png(paste(kuvat, "vtsiom_netti_vs_kannatus.png", sep = ""), width = 1068, height = 841, res = 85)
ggplot(vtsiom_netti_ja_tuki, aes(fill = sota_hyvaksynta, y = prosentti, x = ikaluokat)) +
  geom_bar(position = "fill", stat = "identity") +
  facet_grid(~netti_luokat) +
  geom_text(aes(label = scales::percent(prosentti, accuracy = 1)),
            position = position_stack(vjust = 0.5), 
            fontface = "bold",
            family = "Georgia") +
  scale_fill_manual(values = c(harmaa, punainen, vihrea)) + 
  labs(title = "VTsIOM: Internetin käytön yhteys \"sotaoperaation\" tukemiseen",
    x = "Ikäluokka", y = "Prosenttia ikäluokasta (%)",
    fill = '"Sotaoperaation"\ntukeminen') +
  theme_meduza() +
  theme(strip.text = element_text(face = "bold.italic",
                                  size = 15),
        axis.text.y = element_blank(),
        axis.text.x = element_text(angle = 30)) +
  caption_vtsiom() +
  guides(fill = guide_legend(reverse=TRUE))
ai_logo()
dev.off()

# Laske ikäluokkakohtainen sodan kannatus TV:n katselun perusteella
tv_ja_tuki <- sota_molemmat %>% 
  group_by(ikaluokat, tv_luokat, sota_hyvaksynta) %>% 
  summarise(n = n()) %>% 
  mutate(prosentti = n / sum(n))

# Visualisoi sodan kannatus ikäluokan ja TV:n kulutuksen mukaan
png(paste(kuvat, "vtsiom_tv_vs_kannatus.png", sep = ""), width = 1068, height = 841, res = 85)
ggplot(tv_ja_tuki, aes(fill = sota_hyvaksynta, y = prosentti, x = ikaluokat)) +
  geom_bar(position = "fill", stat = "identity") +
  facet_grid(~tv_luokat) +
  geom_text(aes(label = scales::percent(prosentti, accuracy = 1)),
            position = position_stack(vjust = 0.5), 
            fontface = "bold",
            family = "Georgia") +
  scale_fill_manual(values = c(harmaa, punainen, vihrea)) + 
  labs(title = "VTsIOM: television katselun yhteys \"sotaoperaation\" tukemiseen",
    x = "Ikäluokka", y = "Prosenttia ikäluokasta (%)",
    fill = '"Sotaoperaation"\ntukeminen') +
  theme_meduza() +
  theme(strip.text = element_text(face = "bold.italic",
                                  size = 15),
        axis.text.y = element_blank(),
        axis.text.x = element_text(angle = 30)) +
  caption_vtsiom() +
  guides(fill = guide_legend(reverse=TRUE))
ai_logo()
dev.off()

# Muunna kategorisiksi muuttujiksi
sota_molemmat$kaupunkiluokat <- as.factor(sota_molemmat$kaupunkiluokat)
sota_molemmat$ikaluokat <- as.factor(sota_molemmat$ikaluokat)

# VTSIOM: Osita kaupunki data
vtsiom_kaupunki_ja_koulutus <- sota_molemmat %>% 
  group_by(kaupunkiluokat, koulutusluokat, sota_hyvaksynta) %>% 
  summarise(n = n()) %>% 
  mutate(prosentti = n / sum(n))

# VTSIOM: Visualisoi koulutus ja asuinalue vs. sodan kannatus
png(paste(kuvat, "vtsiom_asuinalue_koulutus_vs_kannatus.png", sep = ""), width = 1068, height = 841, res = 85)
  ggplot(vtsiom_kaupunki_ja_koulutus, aes(fill = sota_hyvaksynta, y = prosentti, x = kaupunkiluokat)) +
  geom_bar(position = "fill", stat = "identity") +
  facet_grid(~koulutusluokat) +
  geom_text(aes(label = scales::percent(prosentti, accuracy = 1)),
            position = position_stack(vjust = 0.5), 
            fontface = "bold",
            family = "Georgia") +
  scale_fill_manual(values = c(harmaa, punainen, vihrea)) +
  scale_x_discrete(limits = c("Miljoonakaupungit", "Suuret kaupungit", "Keskikokoiset kaupungit", "Pienet kaupungit ja kylät"), labels = c("Miljoona-\nkaupungit", "Suuret\nkaupungit", "Keskikokoiset\nkaupungit", "Pienet\nkaupungit\nja kylät")) +
  labs(title = "VTsIOM: asuinpaikan ja koulutustason yhteys \"sotaoperaation\" tukemiseen",
    x = "Asuinalueen luokitus", y = "Prosenttia sotaa tukevista (%)",
    fill = '"Sotaoperaation"\ntukeminen') +
  theme_meduza() +
  theme(strip.text = element_text(face = "bold.italic",
                                  size = 15),
        axis.text.y = element_blank(),
        axis.text.x = element_text(angle = 0)) +
  caption_vtsiom() +
  guides(fill = guide_legend(reverse=TRUE))
  ai_logo()
dev.off()


```

## Riippumaton data

```{r}
# Tuo data
data_suom <- riipp_data %>% 
  rename(vastaajatunnus = ID,
         haastattelu_kesto = IVDur,
         haastattelu_tulos = Result,
         keskeytys_kysymys = Break_off,
         vastaaja_reaktio = Q1000,
         sukupuoli = Q1002,
         ika = Q1003,
         asuinalue_koko = Q1006,
         asuinalue = Q1005,
         tietoisuus_sota = Q1,
         sota_tuki = Q4,
         ukraina_uhka = Q3,
         sota_lahipiiri_tuki = Q5,
         ukraina_reaktio = Q6,
         ukraina_siteet = Q7,
         sota_voitto = Q8,
         sota_voitto_muu = Q8_98T,
         syy_kieltaytya = Q1999,
         syy_kieltaytya_muu = Q1999_6T,
         sota_informaatio_ = Q9_1:Q9_99,
         sotasyy_ = Q2_1:Q2_98T,
         sota_informaatio_2_kuvaus = Q9_2T,
         sota_informaatio_3_kuvaus = Q9_3T,
         sota_informaatio_4_kuvaus = Q9_4T,
         sota_informaatio_5_kuvaus = Q9_5T,
         sota_informaatio_6_kuvaus = Q9_6T,
         sota_informaatio_7_kuvaus = Q9_7T,
         sota_informaatio_8_kuvaus = Q9_8T,
         sota_informaatio_9_kuvaus = Q9_9T,
         sota_informaatio_10_kuvaus = Q9_10T,
         sota_informaatio_11_kuvaus = Q9_11T,
         tunnustus_dnr_lnr = Q10,
         presidentti_kyky = Q11,
         presidentti_tyytyvaisyys = Q12,
         presidentti_valtakausi = Q13,
         perhe_materia_tilanne_mennyt = Q14,
         perhe_materia_tilanne_tuleva = Q15,
         venaja_materia_tilanne_tuleva = Q16,
         koulutus = Q300,
         tyostatus = Q301,
         tyosektori = Q302,
         perhe_asepalvelus = Q303,
         ei_poikia = Q304_97,
         poikia_ = Q304_1:Q304_7,
         poikia_eos = Q304_99,
         poikia_kieltaytyy = Q304_999,
         poikia_maara_ = Q304_1N:Q304_7N,
         talous_pehre = Q305,
         haastattelija_havainnot = Q306
         )


# Filtteröi vain kyselyyn vastanneet
data_suom2 <- data_suom %>% 
  filter(haastattelu_tulos %in% c("Полное"))

# Tällä saadaan oikea paino asetettua
data_suom2_design <- svydesign(ids =~data_suom2$vastaajatunnus,
                              data = data_suom2,
                              weights = data_suom2$weight)

# Painotettu kannatusdata
tab_w <- svytable(~sota_tuki, design = data_suom2_design) %>%
  as.data.frame() %>%
  mutate(prosentti = Freq / sum(Freq))

# Määrittele värit
riipp_harmaa <- "#9E9E9E" # "En osaa sanoa"
riipp_punainen <- "#ff0000" # "Ennemmin en tue"
riipp_vaalean_punainen <- "#ffb700"
riipp_vihrea <- "#63AEA6" # "Ennemmin tuen"
riipp_vaalean_vihrea <- "#04ff00"
musta <- "black"
keltainen <- "#fbff00"

# Arvot
arvot <- c("Ehdottomasti\ntuen", "Ennemmin\ntuen", "Osittain tuen,\nosittain en", "Ennemmin\nen tue", "Ehdottomasti\nen tue", "En osaa\nsanoa", "Kieltäytyy\nvastaamasta")

# Riippumaton tutkijaryhmä: sodan yleiskannatus Likert-asteikolla
png(paste(kuvat, "riipp_kannatus_likert.png", sep = ""), width = 1068, height = 841, res = 85)
ggplot(tab_w, aes(x = sota_tuki, y = prosentti, fill = sota_tuki)) +
  geom_col() +
  scale_x_discrete(limits = tab_w$sota_tuki) +
  # geom_text(aes(label = scales::percent(prosentti, accuracy = 1), vjust = -.6), size = 4) +
  scale_fill_manual(values = c(riipp_vihrea, riipp_vaalean_vihrea, keltainen, riipp_vaalean_punainen, riipp_punainen, riipp_harmaa, musta)) +
  scale_x_discrete(labels = arvot) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  # theme(legend.position = "none") +
  theme_meduza() +
  guides(fill = FALSE) +
  labs(title = 'Riippumaton tutkijaryhmä: Tuetteko "sotaoperaatiota" Ukrainan alueella?',
       x = NULL, y = NULL) +
  caption_riipp() +
  prosentit()
ai_logo()
dev.off()

# Luo uusi 3-luokkainen summamuuttuja sodan tuelle
data_suom2 <- data_suom2 %>% 
  mutate(sota_tuki_2luokka = case_when(
    sota_tuki %in% c(1, 2) ~ "Tuen",
    sota_tuki %in% c(4, 5) ~ "En tue",
    sota_tuki %in% c(3, 6) ~ "En osaa sanoa",
    sota_tuki == 7 ~ "NA"
  ))

# Päivitä paino uuden muuttujan luomisen jälkeen
data_suom2_design <- svydesign(ids =~data_suom2$vastaajatunnus,
                              data = data_suom2,
                              weights = data_suom2$weight)

# Luo painotettu data 3-kolmiluokkaiselle sodan tuelle
sotatuki_3luokkaa_painotettu <- svytable(~sota_tuki_2luokka, design = data_suom2_design) %>% 
  as.data.frame() %>% 
  mutate(prosentti = Freq / sum(Freq))

# Määrittele otsikot visualisointia varten
arvot_3luokkaa <- c("En osaa\nsanoa", "En tue", "Tuen")

# Visualisoi 3-luokkainen painotettu sodan tuki kuva
png(paste(kuvat, "riipp_sota_kannatus_3luokkaa.png", sep = ""), width = 1068, height = 841, res = 85)
sotatuki_3luokkaa_painotettu %>%
  filter(sota_tuki_2luokka != "NA") %>% 
  ggplot(aes(x = sota_tuki_2luokka, y = prosentti, fill = sota_tuki_2luokka)) +
  geom_col() +
  scale_fill_manual(values = c(harmaa, "#D17466", vihrea)) +
  scale_x_discrete(labels = arvot_3luokkaa) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), breaks = c(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7)) +
  theme_meduza() +
  theme(axis.text.x = element_text(
    colour = c(harmaa, "#D17466", vihrea))) +
  guides(fill = FALSE) +
  labs(title = 'Riippumaton tutkijaryhmä: Tuetteko "sotaoperaatiota" Ukrainan alueella?',
       x = NULL, y = NULL) +
  caption_riipp() +
  prosentit()
ai_logo()
dev.off()

# Uudelleen nimeä alueet karttadataa vastaaviksi
data_suom2 <- data_suom2 %>% 
  mutate(asuinalue = recode(asuinalue,
         '1' = 'Adygey',
         '2' = 'Altay',
         '3' = 'Bashkortostan',
         '4' = 'Buryat',
         '5' = 'Dagestan',
         '6' = 'Ingush',
         '7' = 'Kabardin-Balkar',
         '8' = 'Kalmyk',
         '9' = 'Karachay-Cherkess',
         '10' = 'Karelia',
         '11' = 'Komi',
         '12' = 'Mariy-El',
         '13' = 'Mordovia',
         '14' = 'Sakha (Yakutia)',
         '15' = 'North Ossetia',
         '16' = 'Tatarstan',
         '17' = 'Tuva',
         '18' = 'Udmurt',
         '19' = "Khakass",
         "20" = "Chechnya",
         "21" = "Chuvash",
         "22" = "Altay",
         "23" = "Krasnodar",
         "24" = "Krasnoyarsk",
         "25" = "Primor'ye",
         "26" = "Stavropol'",
         "27" = "Khabarovsk",
         "28" = "Amur",
         "29" = "Arkhangel'sk",
         "30" = "Astrakhan'",
         "31" = "Belgorod",
         "32" = "Bryansk",
         "33" = "Vladimir",
         "34" = "Volgograd",
         "35" = "Vologda",
         "36" = "Voronezh",
         "37" = "Ivanovo",
         "38" = "Irkutsk",
         "39" = "Kaliningrad",
         "40" = "Kaluga",
         "42" = "Kemerovo",
         "43" = "Kirov",
         "44" = "Kostroma",
         "45" = "Kurgan",
         "46" = "Kursk",
         "47" = "Leningrad",
         "48" = "Lipetsk",
         "49" = "Maga Buryatdan",
         "50" = "Moskovsskaya",
         "51" = "Murmansk",
         "52" = "Nizhegorod",
         "53" = "Novgorod",
         "54" = "Novosibirsk",
         "55" = "Omsk",
         "56" = "Orenburg",
         "57" = "Orel", # Tämä ehkä joku muu?
         "58" = "Penza",
         "60" = "Pskov",
         "61" = "Rostov",
         "62" = "Ryazan'",
         "63" = "Samara",
         "64" = "Saratov",
         "65" = "Sakhalin",
         "66" = "Sverdlovsk",
         "67" = "Smolensk",
         "68" = "Tambov",
         "69" = "Tver'",
         "70" = "Tomsk",
         "71" = "Tula",
         "72" = "Tyumen'",
         "73" = "Ul'yanovsk",
         "74" = "Chelyabinsk",
         "76" = "Yaroslavl'",
         "77" = "Moskva",
         "78" = "City of St. Petersburg",
         "79" = "Yevrey",
         "83" = "Nenets",
         "86" = "Khanty-Mansiy",
         "87" = "Chukchi Autonomous Okrug",
         "89" = "Yamal-Nenets",
         "90" = "Perm'",
         "91" = "Kamchatka",
         "92" = "Chita", # Selvitä tämä! Ei nyt oikea
         "93" = "Crimea",
         "94" = "Sevastopol",
         "100" = "Other, what exactly:",
         "101" = "Refuse to say"))

# Aseta paino
data_suom2_design <- svydesign(ids =~data_suom2$vastaajatunnus,
                              data = data_suom2,
                              weights = data_suom2$weight)

# Luo koulutusluokat muuttuja
data_suom2 <- data_suom2 %>% 
  mutate(koulutus_luokat = 
           case_when(
             koulutus %in% c(1,2,3,4) ~ "Ei korkeakoulututkintoa",
             koulutus == 5 ~ "Korkeakoulututkinto",
             koulutus %in% c(6, 7) ~ "NA"
           ))

# Luo kaupunkiluokittelut muuttuja
data_suom2 <- data_suom2 %>% 
  mutate(kaupungit_koko =
           case_when(
             asuinalue %in% c("Moskva", "City of St. Petersburg") ~ "Moskova, Pietari",
             asuinalue %in% c("Novosibirsk", "Nizhegorod", "Chelyabinsk", "Samara", "Omsk", "Rostov", "Krasnoyarsk", "Voronezh", "Perm'", "Volgograd", "Crimea", "Tatarstan", "Dagestan", "Chechnya", "Leningrad", "Moskovsskaya") ~ "Miljoonakaupungit ja -alueet",
             asuinalue %in% c("Krasnodar", "Saratov", "Tyumen'", "Ul'yanovsk", "Irkutsk", "Khabarovsk", "Yaroslavl'", "Orenburg", "Tomsk", "Kemerovo", "Ryazan'", "Astrakhan'", "Kirov", "Penza", "Sevastopol", "Lipetsk") ~ "Yli 500,000 asukasta",
             asuinalue %in% c("Kaliningrad", "Tula", "Stavropol'", "Kursk", "Tver'", "Ivanovo", "Bryansk", "Belgorod", "Vladimir", "Chita", "Arkhangel'sk", "Kaluga", "Smolensk", "Vologda", "Kurgan", "Orel", "Tambov", "Murmansk", "Kostroma", "Pskov", "Khanty-Mansiy") ~ "100,000-500,000 asukasta",
             TRUE ~ "Alle 100,000 asukasta, muut"
           ))

# Päivitä paino uuden muuttujan luomisen jälkeen
data_suom2_design <- svydesign(ids =~data_suom2$vastaajatunnus,
                              data = data_suom2,
                              weights = data_suom2$weight)

# Laske painotettu sodan kannatus kaupungin koon mukaan
riipp_kaupunki_koulutus <- as.data.frame(svytable(~kaupungit_koko + koulutus_luokat + sota_tuki_2luokka, data_suom2_design))

# Laske kannatusprosentit asuinalueittain 
riipp_kaupunki_koulutus <- riipp_kaupunki_koulutus %>% 
  filter(koulutus_luokat != "NA",
         sota_tuki_2luokka != "NA") %>% 
  group_by(kaupungit_koko, koulutus_luokat) %>% 
  mutate(prosentti = Freq / sum(Freq))

# Järjestä asuinalueet suurimmasta pienimpään
riipp_kaupunki_koulutus$kaupungit_koko <- 
  factor(riipp_kaupunki_koulutus$kaupungit_koko, levels = c("Moskova, Pietari",
                                                                "Miljoonakaupungit ja -alueet",
                                                                "Yli 500,000 asukasta",
                                                                "100,000-500,000 asukasta",
                                                                "Alle 100,000 asukasta, muut"))

png(paste(kuvat, "riipp_kaupunki_koulutus_vs_kannatus.png", sep = ""), width = 1068, height = 841)
riipp_kaupunki_koulutus %>% 
  ggplot(aes(fill = sota_tuki_2luokka, y = prosentti, x = (kaupungit_koko))) +
    geom_bar(position = "fill", stat = "identity") +
  facet_grid(~koulutus_luokat) +
    geom_text(aes(label = scales::percent(prosentti, accuracy = 1)),
            position = position_stack(vjust = 0.5), 
            fontface = "bold",
            family = "Georgia") +
  scale_fill_manual(values = c(harmaa, punainen, vihrea)) +
  scale_x_discrete(labels = c("Moskova,\nPietari",
                              "Miljoona-\nkaupungit\nja -alueet",
                              "500,000-\n950,000\nasukkaan\nkaupungit",
                              "100,000-\n500,000\nasukasta",
                              "Alle 100,000\nasukasta, muut")) +
  labs(title = 'Riippumaton tutkijaryhmä: asuinpaikan ja koulutustason yhteys "sotaoperaation"\ntukemiseen',
    x = "Asuinalueen luokitus", y = "Prosenttia sotaa tukevista (%)",
    fill = '"Sotaoperaation"\ntukeminen') +
  theme_meduza() +
  theme(strip.text = element_text(face = "bold.italic",
                                  size = 15),
        axis.text.y = element_blank(),
        axis.text.x = element_text(angle = 0)) +
  caption_riipp() +
  guides(fill = guide_legend(reverse=TRUE))
ai_logo()
dev.off()

# # Asuinalue- ja koulutusdata
# riipp_kaupunki_ja_koulutus <- data_suom2 %>% 
#   group_by(asuinalue_koko, koulutus_luokat, sota_tuki_2luokka) %>% 
#   filter(sota_tuki_2luokka != "NA",
#          koulutus_luokat != "NA",
#          asuinalue_koko != 4) %>% 
#   summarise(n = n()) %>% 
#   mutate(prosentti = n / sum(n))
# 
# # Visualisoi ja tallenna asuinalueen ja koulutuksen yhteys kannatukseen
# png("riipp_kaupunki_koulutus_vs_kannatus.png", width = 1068, height = 841, res = 85)
# ggplot(riipp_kaupunki_ja_koulutus, aes(fill = sota_tuki_2luokka, y = prosentti, x = asuinalue_koko)) +
#   geom_bar(position = "fill", stat = "identity") +
#   facet_grid(~koulutus_luokat) +
#     geom_text(aes(label = scales::percent(prosentti, accuracy = 1)),
#             position = position_stack(vjust = 0.5), 
#             fontface = "bold",
#             family = "Georgia") +
#   scale_fill_manual(values = c(harmaa, punainen, vihrea)) +
#   scale_x_discrete(limits = c(1,2,3), labels = c("Kaupungit", "Kylä, maaseutu, taajamat", "Kaupungin tapainen\ntaajama")) +
#   labs(title = 'Riippumaton tutkijaryhmä: asuinpaikan ja koulutustason yhteys "sotaoperaation"\ntukemiseen',
#     x = "Asuinalueen luokitus", y = "Prosenttia sotaa tukevista (%)",
#     fill = '"Sotaoperaation"\ntukeminen') +
#   theme_meduza() +
#   theme(strip.text = element_text(face = "bold.italic",
#                                   size = 15),
#         axis.text.y = element_blank(),
#         axis.text.x = element_text(angle = 30)) +
#   caption_riipp() +
#   guides(fill = guide_legend(reverse=TRUE))
# ai_logo()
# dev.off()

# Data iän yhteydestä sodan hyväksyntään
riipp_sota_tuki_vs_ika <- data_suom2 %>% 
  select(ika, sota_tuki_2luokka) %>% 
  filter(sota_tuki_2luokka != "NA") %>% 
  group_by(ika, sota_tuki_2luokka) %>% 
  summarise(n = n()) %>% 
  mutate(prosentti_ika = n / sum (n)) %>% 
  ungroup()

# Muunna sodan hyväksyntä muuttuja kategoriseksi
riipp_sota_tuki_vs_ika$sota_tuki_2luokka <- as.factor(riipp_sota_tuki_vs_ika$sota_tuki_2luokka)

# Riippumaton data: visualisoi sodan hyväksyntä suhteessa ikään
png(paste(kuvat, "riipp_ika_vs_kannatus.png", sep = ""), width = 1068, height = 841, res = 85)
riipp_sota_tuki_vs_ika %>% 
  filter(ika <= 75) %>%
  ggplot(aes(x = ika, y = prosentti_ika, group = sota_tuki_2luokka)) +
  geom_smooth(aes(color = sota_tuki_2luokka), se = F) +
  scale_x_continuous(breaks = seq(20, 70, 10)) +
  theme_meduza() +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), breaks = seq(.1, .8, .1)) +
  scale_color_manual(values = c("black", "#D37463", vihrea)) +
  labs(title = 'Riippumaton tutkijaryhmä: iän yhteys "sotaoperaation" kannatukseen (trendiviivat)',
       y = 'Prosenttia ikäluokasta (%)',
       x = "Vastaajan ikä vuosina",
       color = '"Sotaoperaation" hyväksyntä') +
  guides(color = guide_legend(reverse=TRUE)) +
  caption_riipp()
ai_logo()
dev.off()

# Sukupuolen yhteys kannatukseen
riipp_sota_sukupuoli <- data_suom2 %>% 
  select(sukupuoli, sota_tuki_2luokka, ika) %>%
  filter(sota_tuki_2luokka != "NA") %>% 
  group_by(sukupuoli, ika, sota_tuki_2luokka) %>% 
  summarise(n = n()) %>% 
  mutate(prosentti_ika = n / sum(n)) %>% 
  ungroup()

# Muunna sodan hyväksyntä muuttuja kategoriseksi
riipp_sota_sukupuoli$sota_tuki_2luokka <- as.factor(riipp_sota_sukupuoli$sota_tuki_2luokka)
# Anna uudet arvot sukupuoli muuttujille
riipp_sota_sukupuoli <- riipp_sota_sukupuoli %>% 
  mutate(sukupuoli = recode(sukupuoli, "1" = "Mies", "2" = "Nainen"))

png(paste(kuvat, "riipp_ika_sukupuoli_vs_kannatus.png", sep = ""), width = 1068, height = 841, res = 85)
riipp_sota_sukupuoli %>% 
  filter(ika <= 75) %>% 
  filter(sota_tuki_2luokka == "En tue") %>% 
  ggplot(aes(x = ika, y = prosentti_ika, group = sukupuoli)) +
  geom_smooth(aes(color = sukupuoli), se = F) +
  scale_x_continuous(breaks = seq(20, 70, 10)) +
  theme_meduza() +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), breaks = seq(.1, .7, .1)) +
  guides(color = guide_legend(reverse=TRUE)) +
  scale_color_manual(values = c("black", vihrea)) +
  labs(title = 'Riippumaton tutkijaryhmä: sukupuolen ja iän yhteys "sotaoperaation" kannatukseen (trendiviivat)',
       y = 'Prosenttia miehistä ja naisista ikäluokittain (%)',
       x = "Vastaajan ikä vuosina",
       color = '"Ennemmin vastustan"\nsukupuolittain') +
  caption_riipp()
ai_logo()
dev.off()
## Tallennettu spekseillä Width 1125 ja Heigth 841, tiedostonimi: riipp_ika_sukupuoli.png

# Luo ikäluokat muuttuja
data_suom2 <- data_suom2 %>% 
  mutate(ikaluokat =
             case_when(ika >= 18 & ika <= 30 ~ "18–30-vuotiaat",
                     ika >= 31 & ika <= 45 ~ "31–45-vuotiaat",
                     ika >= 46 & ika <= 60 ~ "46–60-vuotiaat",
                     ika > 60 ~ "Yli 60-vuotiaat")
         )

# Päivitä paino uuden muuttujan luomisen jälkeen
data_suom2_design <- svydesign(ids =~data_suom2$vastaajatunnus,
                              data = data_suom2,
                              weights = data_suom2$weight)

# Laske painotettu sodan kannatus kaupungin koon mukaan
# riipp_kaupunki_koulutus <- as.data.frame(svytable(~kaupungit_koko + koulutus_luokat + sota_tuki_2luokka, data_suom2_design))

riipp_netti_ja_tuki <- as.data.frame(svytable(~ikaluokat + sota_informaatio_3 + sota_tuki_2luokka, data_suom2_design))


riipp_netti_ja_tuki <- riipp_netti_ja_tuki %>% 
  filter(sota_tuki_2luokka != "NA") %>% 
  group_by(ikaluokat, sota_informaatio_3) %>% 
  mutate(prosentti = Freq / sum(Freq))


# Muunna kaksiluokkaiseksi kategoriseksi muuttujaksi
riipp_netti_ja_tuki$sota_informaatio_3 <- factor(riipp_netti_ja_tuki$sota_informaatio_3, levels = c("0", "1"),
                                              labels = c("Tietolähde: muu kuin Internet", "Tietolähde: Internet"))

# Tallenna kuva
png(paste(kuvat, "riipp_netti_vs_tuki.png", sep = ""), width = 1068, height = 841, res = 85)
riipp_netti_ja_tuki %>% 
  ggplot(aes(fill = sota_tuki_2luokka, y = prosentti, x = ikaluokat)) +
      geom_bar(position = "fill", stat = "identity") +
  facet_grid(~sota_informaatio_3) +
  geom_text(aes(label = scales::percent(prosentti, accuracy = 1)),
            position = position_stack(vjust = 0.5), 
            fontface = "bold",
            family = "Georgia") +
  scale_fill_manual(values = c(harmaa, punainen, vihrea)) + 
  scale_x_discrete(labels = c("18–30-\nvuotiaat",
                              "31–45-\nvuotiaat",
                              "46–60-\nvuotiaat",
                              "Yli 60-\nvuotiaat")) +
  labs(title = "Riippumaton tutkijaryhmä: Internetin käytön yhteys \"sotaoperaation\" tukemiseen",
    x = "Ikäluokka", y = "Prosenttia ikäluokasta (%)",
    fill = '"Sotaoperaation"\ntukeminen') +
  theme_meduza() +
  theme(strip.text = element_text(face = "bold.italic",
                                  size = 15),
        axis.text.y = element_blank(),
        axis.text.x = element_text(angle = 0)) +
  caption_riipp() +
  guides(fill = guide_legend(reverse=TRUE))
ai_logo()
dev.off()

# # Laske prosentit netin käytön yhteydestä sodan kannatukselle
# riipp_netti_ja_tuki2 <- data_suom2 %>% 
#   group_by(ikaluokat, sota_informaatio_3, sota_tuki_2luokka) %>% 
#   filter(sota_tuki_2luokka != "NA") %>% 
#   summarise(n = n()) %>% 
#   mutate(prosentti = n / sum(n))
# 
# # Muunna kaksiluokkaiseksi kategoriseksi muuttujaksi
# riipp_netti_ja_tuki2$sota_informaatio_3 <- factor(riipp_netti_ja_tuki2$sota_informaatio_3, levels = c("0", "1"),
#                                               labels = c("Tietolähde: muu kuin Internet", "Tietolähde: Internet"))
# 
# 
# # Riippumaton data visualisointi: netti ja ikä vs. sodan kannatus 
# png("riipp_netti_ikaluokat_vs_kannatus2.png", width = 1068, height = 841, res = 85)
# ggplot(riipp_netti_ja_tuki2, aes(fill = sota_tuki_2luokka, y = prosentti, x = ikaluokat)) +
#   geom_bar(position = "fill", stat = "identity") +
#   facet_grid(~sota_informaatio_3) +
#   geom_text(aes(label = scales::percent(prosentti, accuracy = 1)),
#             position = position_stack(vjust = 0.5), 
#             fontface = "bold",
#             family = "Georgia") +
#   scale_fill_manual(values = c(harmaa, punainen, vihrea)) + 
#   labs(title = "Riippumaton tutkijaryhmä: Internetin käytön yhteys \"sotaoperaation\" tukemiseen",
#     x = "Ikäluokka", y = "Prosenttia ikäluokasta (%)",
#     fill = '"Sotaoperaation"\ntukeminen') +
#   theme_meduza() +
#   theme(strip.text = element_text(face = "bold.italic",
#                                   size = 15),
#         axis.text.y = element_blank(),
#         axis.text.x = element_text(angle = 30)) +
#   caption_riipp() +
#   guides(fill = guide_legend(reverse=TRUE))
# ai_logo()
# dev.off()

# Luo uusi data TV:n katselun ja sodan kannatuksen yhteydestä
riipp_tv_ja_tuki <- data_suom2 %>% 
  group_by(ikaluokat, sota_informaatio_2, sota_tuki_2luokka) %>% 
  filter(sota_tuki_2luokka != "NA") %>% 
  summarise(n = n()) %>% 
  mutate(prosentti = n / sum(n))

# Uudet nimet TV-muuttujan arvoille
riipp_tv_ja_tuki$sota_informaatio_2 <- factor(riipp_tv_ja_tuki$sota_informaatio_2, levels = c("0", "1"),
                                              labels = c("Tietolähde: muu kuin televisio", "Tietolähde: televisio"))


# Riippumaton data visualisointi: TV ja ikä vs. sodan kannatus 
png(paste(kuvat, "riipp_tv_vs_tuki.png", sep = ""), width = 1068, height = 841, res = 85)
ggplot(riipp_tv_ja_tuki, aes(fill = sota_tuki_2luokka, y = prosentti, x = ikaluokat)) +
  geom_bar(position = "fill", stat = "identity") +
  facet_grid(~sota_informaatio_2) +
  geom_text(aes(label = scales::percent(prosentti, accuracy = 1)),
            position = position_stack(vjust = 0.5), 
            fontface = "bold",
            family = "Georgia") +
  scale_fill_manual(values = c(harmaa, punainen, vihrea)) + 
  labs(title = "Riippumaton tutkijaryhmä: television katselun yhteys \"sotaoperaation\" tukemiseen",
    x = "Ikäluokka", y = "Prosenttia ikäluokasta (%)",
    fill = '"Sotaoperaation"\ntukeminen') +
  theme_meduza() +
  theme(strip.text = element_text(face = "bold.italic",
                                  size = 15),
        axis.text.y = element_blank(),
        axis.text.x = element_text(angle = 30)) +
  caption_riipp() +
  guides(fill = guide_legend(reverse=TRUE))
ai_logo()
dev.off()


```


# Riippumaton data: karttavisualisointi

```{r}
russia <- ne_states(country = "russia", returnclass = "sf")

# # # Helpottaa rivinumeroiden etsimisessä
# venaja <- as.data.frame(russia)
# 
# venaja %>% 
#   select(region) %>% 
#   distinct()
# # row.names(venaja) <- NULL
# 
# # Määrittele puuttuvat federaatiopiiri vektorit
# pohjois_kaukasia <- c("Dagestan", "Ingush", "Kabardin-Balkar", "Karachay-Cherkess", "North Ossetia", "Chechnya", "Stavropol'")
# etela <- c("Adygey", "Kalmyk", "Crimea", "Krasnodar", "Astrakhan'", "Volgograd", "Rostov", "Sevastopol")
# 
# # Etsi em. vektoreiden perusteella oikeat rivinumerot
# venaja[venaja$name %in% pohjois_kaukasia, ]
# venaja[venaja$name %in% etela, ]

# Nimeä federaatiopiirit uudelleen rivinumeroiden perusteella
russia[4, "region"] <- "North Caucasian" # Karachay-Cherkess
russia[5, "region"] <- "North Caucasian" # Kabardin-Balkar
russia[6, "region"] <- "North Caucasian" # Norh Ossetia
russia[7, "region"] <- "North Caucasian" # Ingush
russia[8, "region"] <- "North Caucasian" # Chechnya
russia[9, "region"] <- "North Caucasian" # Dagestan
russia[85, "region"] <- "North Caucasian" # Stavropol
russia[3, "region"] <- "Southern" # Krasnodar
russia[19, "region"] <- "Southern" # Rostov
russia[35, "region"] <- "Southern" # Astrakhan
russia[36, "region"] <- "Southern" # Volgograd
russia[37, "region"] <- "Southern" # Crimea
russia[40, "region"] <- "Southern" # Sevastopol
russia[48, "region"] <- "Southern" # Kalmuk
russia[86, "region"] <- "Southern" # Adugey

# Uudelleen nimeä alueet karttadataa vastaaviksi
# data_suom2 <- data_suom2 %>% 
#   mutate(asuinalue = recode(asuinalue,
#          '1' = 'Adygey',
#          '2' = 'Altay',
#          '3' = 'Bashkortostan',
#          '4' = 'Buryat',
#          '5' = 'Dagestan',
#          '6' = 'Ingush',
#          '7' = 'Kabardin-Balkar',
#          '8' = 'Kalmyk',
#          '9' = 'Karachay-Cherkess',
#          '10' = 'Karelia',
#          '11' = 'Komi',
#          '12' = 'Mariy-El',
#          '13' = 'Mordovia',
#          '14' = 'Sakha (Yakutia)',
#          '15' = 'North Ossetia',
#          '16' = 'Tatarstan',
#          '17' = 'Tuva',
#          '18' = 'Udmurt',
#          '19' = "Khakass",
#          "20" = "Chechnya",
#          "21" = "Chuvash",
#          "22" = "Altay",
#          "23" = "Krasnodar",
#          "24" = "Krasnoyarsk",
#          "25" = "Primor'ye",
#          "26" = "Stavropol'",
#          "27" = "Khabarovsk",
#          "28" = "Amur",
#          "29" = "Arkhangel'sk",
#          "30" = "Astrakhan'",
#          "31" = "Belgorod",
#          "32" = "Bryansk",
#          "33" = "Vladimir",
#          "34" = "Volgograd",
#          "35" = "Vologda",
#          "36" = "Voronezh",
#          "37" = "Ivanovo",
#          "38" = "Irkutsk",
#          "39" = "Kaliningrad",
#          "40" = "Kaluga",
#          "42" = "Kemerovo",
#          "43" = "Kirov",
#          "44" = "Kostroma",
#          "45" = "Kurgan",
#          "46" = "Kursk",
#          "47" = "Leningrad",
#          "48" = "Lipetsk",
#          "49" = "Maga Buryatdan",
#          "50" = "Moskovsskaya",
#          "51" = "Murmansk",
#          "52" = "Nizhegorod",
#          "53" = "Novgorod",
#          "54" = "Novosibirsk",
#          "55" = "Omsk",
#          "56" = "Orenburg",
#          "57" = "Orel", # Tämä ehkä joku muu?
#          "58" = "Penza",
#          "60" = "Pskov",
#          "61" = "Rostov",
#          "62" = "Ryazan'",
#          "63" = "Samara",
#          "64" = "Saratov",
#          "65" = "Sakhalin",
#          "66" = "Sverdlovsk",
#          "67" = "Smolensk",
#          "68" = "Tambov",
#          "69" = "Tver'",
#          "70" = "Tomsk",
#          "71" = "Tula",
#          "72" = "Tyumen'",
#          "73" = "Ul'yanovsk",
#          "74" = "Chelyabinsk",
#          "76" = "Yaroslavl'",
#          "77" = "Moskva",
#          "78" = "City of St. Petersburg",
#          "79" = "Yevrey",
#          "83" = "Nenets",
#          "86" = "Khanty-Mansiy",
#          "87" = "Chukchi Autonomous Okrug",
#          "89" = "Yamal-Nenets",
#          "90" = "Perm'",
#          "91" = "Kamchatka",
#          "92" = "Chita", # Selvitä tämä! Ei nyt oikea
#          "93" = "Crimea",
#          "94" = "Sevastopol",
#          "100" = "Other, what exactly:",
#          "101" = "Refuse to say"))

# Aseta paino
data_suom2_design <- svydesign(ids =~data_suom2$vastaajatunnus,
                              data = data_suom2,
                              weights = data_suom2$weight)

# Laske painotetut keskiarvot sodan tuelle alueittain
riipp_kartta_data_painotettu <- as.data.frame(svytable(~sota_tuki_2luokka + asuinalue, data_suom2_design))

# Laske asuinaluekohtaiset prosentit sodan kannatukselle
riipp_kartta_data_painotettu <- riipp_kartta_data_painotettu %>% 
  group_by(asuinalue) %>% 
  mutate(prosentti = Freq / sum(Freq)) %>% 
  mutate(name = asuinalue)

# Yhdistä karttadata sodan kannatusdataan
riipp_kartta_graafi_data <- merge(russia, riipp_kartta_data_painotettu, by.x = "name", by.y = "name", all = TRUE)

# riipp_kartta_data_painotettu %>% 
#   filter(sota_tuki_2luokka == "Tuen") %>% 
#   select(asuinalue, prosentti) %>% 
#   arrange(desc(prosentti))

# Riippumaton tutkijaryhmä: visualisoi ja tallenna sodan kannatusdata alueittain
png(paste(kuvat, "riipp_kannattus_kartta.png", sep = ""), width = 987, height = 816, res = 85)
riipp_kartta_graafi_data %>% 
  filter((sota_tuki_2luokka == "Tuen") %>% replace_na(TRUE)) %>% # Pitää puuttuvat arvot karttavisualisoinnissa
  ggplot(aes(geometry = geometry, fill = prosentti)) +
  geom_sf() +
  xlim(15, 190) +
  ylim(40, 83) +
  theme_meduza() +
  labs(fill = '"Sotaoperaation"\ntuki (%)',
       title = 'Riippumaton tutkijaryhmä: "sotaoperaation" kannatus alueittain Venäjällä') +
  scale_fill_viridis_c(labels = scales::percent_format(accuracy = 1)) +
  theme(axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        legend.text = element_text(face = "bold"),
        legend.title = element_text(face = "bold"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()
        ) +
  caption_riipp()
grid::grid.raster(
    logo_ai,
    x = 0.02,
    y = 0.2,
    just = c("left", "bottom"), width = unit(0.5, "inches")
  )
dev.off()

```

# VTsIOM: karttavisualisointi


```{r}
# Aseta paino
vtsiom_kartta_data_design <- svydesign(ids =~sota_molemmat$vastaaja_tunnus,
                              data = sota_molemmat,
                              weights = sota_molemmat$otanta_paino)

# Laske painotetut prosenttijaukamat sodan tuelle alueittain
vtsiom_kartta_data_painotettu <- svytable(~sota_hyvaksynta + federaatio_piiri, vtsiom_kartta_data_design)
vtsiom_kartta_data_painotettu <- as.data.frame(vtsiom_kartta_data_painotettu)
vtsiom_kartta_data_painotettu <- vtsiom_kartta_data_painotettu %>% 
  group_by(federaatio_piiri) %>% 
  mutate(prosentti = Freq / sum(Freq))

# Lisää rnaturalearth karttadatan mukaiset muuttujanimet
vtsiom_kartta_data_painotettu <- vtsiom_kartta_data_painotettu %>% 
  mutate(
    region = 
      case_when(
        federaatio_piiri == "Eteläinen federaatiopiiri" ~ "Southern",
        federaatio_piiri == "Pohjois-Kaukasian federaatiopiiri" ~ "North Caucasian",
        federaatio_piiri == "Kaukoidän federaatiopiiri" ~ "Far Eastern",
        federaatio_piiri == "Volgan federaatiopiiri" ~ "Volga",
        federaatio_piiri == "Siperian federaatiopiiri" ~ "Siberian",
        federaatio_piiri == "Keskinen federaatiopiiri" ~ "Central",
        federaatio_piiri == "Uralin federaatiopiiri" ~ "Urals",
        federaatio_piiri == "Luoteinen federaatiopiiri" ~ "Northwestern"
      )
  )

# Yhdistä VTsIOMin sodan kannatusdata karttadataan
vtsiom_kartta_graafi_data <- merge(russia, vtsiom_kartta_data_painotettu, by.x = "region", by.y = "region", all = TRUE)

# VTsIOM: visualisoi ja tallenna sodan kannatusdata federaatiopiireittäin
png(paste(kuvat, "vtsiom_kannatus_kartta.png", sep = ""), width = 987, height = 816, res = 85)
vtsiom_kartta_graafi_data %>% 
  filter(sota_hyvaksynta == "Ennemmin tuen") %>% 
  ggplot(aes(geometry = geometry, fill = prosentti)) +
  geom_sf() +
  xlim(15, 190) +
  ylim(40, 83) +
  theme_meduza() +
  labs(fill = '"Sotaoperaation"\ntuki (%)',
       title = 'VTsIOM: "sotaoperaation" tuki federaatiopiireittäin Venäjällä') +
  scale_fill_viridis_c(labels = scales::percent_format(accuracy = 1)) +
  theme(axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        legend.text = element_text(face = "bold"),
        legend.title = element_text(face = "bold"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()
        ) +
  caption_vtsiom()
grid::grid.raster(
    logo_ai,
    x = 0.02,
    y = 0.2,
    just = c("left", "bottom"), width = unit(0.5, "inches")
  )
dev.off()

```

# Putinin / presidentin suosio data

```{r}
# Define and read URL
levada_link <- "https://www.levada.ru/indikatory/odobrenie-organov-vlasti/"
levada_page <- read_html(levada_link)
# Import the table
levada_table <- levada_page %>% 
  html_nodes("table.datatable") %>% 
  html_table() %>% 
  .[[1]] %>% 
  as.data.frame()
# Name rows
rownames(levada_table) <- c("date", "approve", "dont_approve", "no_answer")
# Transpose the table
levada_table <- as.data.frame(t(levada_table))
# Make a new character string date variable
levada_table$date2 <- as.character(levada_table$date)
# Rename some weird looking date observations
## for year 2000
levada_table$date2[levada_table$date2 == "1.2"] <- "1.2000"
levada_table$date2[levada_table$date2 == "2.2"] <- "2.2000"
levada_table$date2[levada_table$date2 == "3.2"] <- "3.2000"
levada_table$date2[levada_table$date2 == "4.2"] <- "4.2000"
levada_table$date2[levada_table$date2 == "5.2"] <- "5.2000"
levada_table$date2[levada_table$date2 == "6.2"] <- "6.2000"
levada_table$date2[levada_table$date2 == "7.2"] <- "7.2000"
levada_table$date2[levada_table$date2 == "8.2"] <- "8.2000"
levada_table$date2[levada_table$date2 == "9.2"] <- "9.2000"
levada_table$date2[levada_table$date2 == "10.2"] <- "10.2000"
levada_table$date2[levada_table$date2 == "11.2"] <- "11.2000"
levada_table$date2[levada_table$date2 == "12.2"] <- "12.2000"
## For year 2010
levada_table$date2[levada_table$date2 == "1.201"] <- "1.2010"
levada_table$date2[levada_table$date2 == "2.201"] <- "2.2010"
levada_table$date2[levada_table$date2 == "3.201"] <- "3.2010"
levada_table$date2[levada_table$date2 == "4.201"] <- "4.2010"
levada_table$date2[levada_table$date2 == "5.201"] <- "5.2010"
levada_table$date2[levada_table$date2 == "6.201"] <- "6.2010"
levada_table$date2[levada_table$date2 == "7.201"] <- "7.2010"
levada_table$date2[levada_table$date2 == "8.201"] <- "8.2010"
levada_table$date2[levada_table$date2 == "9.201"] <- "9.2010"
levada_table$date2[levada_table$date2 == "10.201"] <- "10.2010"
levada_table$date2[levada_table$date2 == "11.201"] <- "11.2010"
levada_table$date2[levada_table$date2 == "12.201"] <- "12.2010"
## For year 2020
levada_table$date2[levada_table$date2 == "1.202"] <- "1.2020"
levada_table$date2[levada_table$date2 == "2.202"] <- "2.2020"
levada_table$date2[levada_table$date2 == "3.202"] <- "3.2020"
levada_table$date2[levada_table$date2 == "4.202"] <- "4.2020"
levada_table$date2[levada_table$date2 == "5.202"] <- "5.2020"
levada_table$date2[levada_table$date2 == "6.202"] <- "6.2020"
levada_table$date2[levada_table$date2 == "7.202"] <- "7.2020"
levada_table$date2[levada_table$date2 == "8.202"] <- "8.2020"
levada_table$date2[levada_table$date2 == "9.202"] <- "9.2020"
levada_table$date2[levada_table$date2 == "10.202"] <- "10.2020"
levada_table$date2[levada_table$date2 == "11.202"] <- "11.2020"
levada_table$date2[levada_table$date2 == "12.202"] <- "12.2020"
# Create a new POSIXct date variable denoting month and year
levada_table_2 <- levada_table %>% 
  mutate(date_parsed2= parse_date_time(levada_table$date2, "%m.%Y"))
# Create a new table without unnecessary variables
levada_table_3 <- levada_table_2 %>% 
  mutate(approve_prop = approve*0.01, # convert to proportions i.e. percentages
         dont_approve_prop = dont_approve*0.01, # convert to proportions i.e. percentages
         no_answer_prop = no_answer*0.01) %>% # convert to proportions i.e. percentages
  select(date_parsed2:no_answer_prop) %>% # select only needed variables
  rename(date = date_parsed2) # rename final date variable
# Add percentages column to the dataset
levada_table_3 <- levada_table_3 %>% 
  dplyr::mutate(approve_perc = scales::percent(approve_prop, accuracy = 1, trim = F),
                dont_approve_perc = scales::percent(dont_approve_prop, accuracy = 1, trim = F),
                no_answer_perc = scales::percent(no_answer_prop, accuracy = 1, trim = F))


# Tuo VTsIOMin presidentin hyväksyntä data
vtsiom <- here::here("data/vtsiom_state_institutions.xlsx") %>% 
  readxl::read_excel(sheet = 3)

vtsiom$vtsiom_prop <- vtsiom$rating*0.01
levada_table_3$levada_prop <- levada_table_3$approve_prop

# Yhdistä Levadan ja VTsOMin rankingit
suosio_levada_vtsiom <- merge(vtsiom, levada_table_3, by = "date", all = TRUE)

# Visualisoi presidentin suosio data
vtsiom_levada_rankingit <- ggplot(suosio_levada_vtsiom, aes(x = date)) +
  geom_line(data = suosio_levada_vtsiom[!is.na(suosio_levada_vtsiom$levada_prop),], aes(y = levada_prop, color = "Levada-keskus")) +
  geom_line(data = suosio_levada_vtsiom[!is.na(suosio_levada_vtsiom$vtsiom_prop),], aes(y = vtsiom_prop, color = "VTsIOM")) +
  ggplot2::labs(x = "Vuosi",
       title = 'Hyväksyn Vladimir Putinin toiminnan Venäjän presidenttinä/pääministerinä ("Kyllä"-%)',
       y = NULL) +
  scale_y_continuous(labels = scales::label_percent(accuracy = 1)) +
  # theme(panel.background = element_rect(fill = "gray96")) +
  scale_color_manual(name = "Datan lähde",
                     values = c("Levada-keskus" = "black", "VTsIOM" = vihrea)) + 
  theme_meduza() +
  caption_ranking()

# Tallenna presidentin suosio ranking kuva
png(paste(kuvat, "levada_vtsiom_rankingit.png", sep = ""), width = 1068, height = 841, res = 85)
vtsiom_levada_rankingit
ai_logo()
dev.off()


```

# Russian Field

```{r}
# Tuo data
rf <- here::here('data/“RF_26-28.02.2022”.sav') %>% 
  read_spss() %>% 
  janitor::clean_names()

# Määritä paino
rf_design <- svydesign(ids =~1,
                       data = rf,
                       weights = rf$vtpv)

# Laske yleiskannatuksen prosenttijakauma
rf_table <- svytable(~q11, design = rf_design) %>% 
  as.data.frame() %>% 
  mutate(prosentti = Freq / sum(Freq))

# rf %>% 
#   select(q11) %>% 
#   look_for()
# 
# rf %>%
#   select(q11) %>%
#   rdhs::get_variable_labels()
# 
# rf %>% 
#   count()

# Visualisoi Russian Field kannatusdata
rf_kannatus <- rf_table %>% 
  group_by(q11) %>% 
  ggplot(aes(x = q11, y = prosentti, fill = q11)) +
  geom_col() +
  scale_fill_manual(values = c(riipp_vihrea, riipp_vaalean_vihrea, riipp_vaalean_punainen, riipp_punainen, keltainen)) +
  scale_x_discrete(labels = c("Ehdottomasti tuen", 
                              "Ennemmin tuen",
                              "Ennemmin en tue",
                              "Ehdottomasti en tue",
                              "En osaa sanoa")) +
  prosentit() +
  theme_meduza() +
    scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs(title = 'Russian Field: tuetteko Venäjän sotatoimia Ukrainan alueella?',
       y = NULL,
       x = NULL) +
  guides(fill = FALSE) +
  caption_rf()

# Tallenna kuva
png(paste(kuvat, "rf_kannatus.png", sep = ""), width = 1068, height = 841, res = 85)
rf_kannatus
ai_logo()
dev.off()


```


