---
title: "Maakoodit suomeksi"
author: "Eemil Mitikka"
date: "2/14/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(rvest)
library(here)
library(ggrepel)

```

```{r}
linkki <- "https://fi.wikipedia.org/wiki/Luettelo_ISO_3166_-standardin_koodeista"
verkkosivu <- read_html(linkki)

maakoodit <- verkkosivu %>% 
  html_nodes("table") %>% 
  .[1] %>% 
  html_table() %>% 
  .[[1]] %>% 
  rename(nimi_suom = "Lyhyt nimi suomeksi",
         nimi_eng = "Lyhyt nimi englanniksi [1]",
         "2_kirj_koodi" = "2-kirjaiminen koodi [1]",
         "3_kirj_koodi" = "3-kirjaiminen koodi [2]",
         "num_koodi" = "Numeerinen koodi [2]",
         "aluekoodi" = "Aluekoodi") 

maakoodit$nimi_eng <- str_to_title(maakoodit$nimi_eng)

vdem <- here("data/vdem_democracy_index") %>% 
  read.csv() %>% 
  rename("3_kirj_koodi" = country_text_id)

# Import the oil price data
link <- "https://statisticstimes.com/economy/countries-by-petrol-prices-and-gdp-per-capita.php"
webpage <- read_html(link)
# Read the HTML table
oljy_hinnat <- webpage %>% 
  html_nodes("table") %>% 
  .[2] %>% 
  html_table() %>% 
  .[[1]]
# Remove the first row
oljy_hinnat <- oljy_hinnat[-1,]

# Subset the democracy data
libdem <- vdem %>% 
  filter(year == 2020) %>% 
  select(country_name, "3_kirj_koodi", year, v2x_libdem) %>% 
  rename(Country = country_name)

# Rename some countries
libdem$Country[libdem$Country == "Burma/Myanmar"] <- "Burma"
libdem$Country[libdem$Country == "United States of America"] <- "USA"
libdem$Country[libdem$Country == "Central African Republic"] <- "Central African Rep."
libdem$Country[libdem$Country == "Democratic Republic of the Congo"] <- "DR Congo"
libdem$Country[libdem$Country == "Trinidad and Tobago"] <- "Trinidad & Tobago"
libdem$Country[libdem$Country == "Bosnia and Herzegovina"] <- "Bosnia & Herz."
libdem$Country[libdem$Country == "North Macedonia"] <- "Northern Macedonia"

# Put all data frames into list
df_list <- list(libdem, oljy_hinnat)

# Merge all data frames in list
full_data <- Reduce(function(x, y) merge(x, y, all=TRUE), df_list)

valmis_lista <- list(full_data, maakoodit)

oljy_vs_demokratia <- Reduce(function(x, y) merge(x, y, all=TRUE), valmis_lista)


taulukot_lista <- list(maakoodit, vdem)

koko_data <- Reduce(function(x, y) merge(x, y, all=TRUE), taulukot_lista)

koko_data %>% 
  distinct(nimi_suom)

# Viimestele taulukko visualisointia varten
oljy_vs_demokratia <- oljy_vs_demokratia %>% 
  select(nimi_suom, "Gasoline/Petrol Prices per liter", v2x_libdem) %>% 
  na.omit() %>% 
  arrange(nimi_suom) %>% 
  rename(oljy_litrahinta_usd = "Gasoline/Petrol Prices per liter",
         demokratia_indeksi_vdem = v2x_libdem)

# Muuta bensan hinta numeeriseksi muuttujaksi
oljy_vs_demokratia$oljy_litrahinta_usd <- as.double(oljy_vs_demokratia$oljy_litrahinta_usd)

# Valmis visualisointi: bensan hinta vs. demokratia
oljy_vs_demokratia %>% 
  ggplot(aes(x = demokratia_indeksi_vdem, y = oljy_litrahinta_usd)) +
  geom_point(color = ifelse(oljy_vs_demokratia$nimi_suom %in% c("Suomi",
                                                                "Ruotsi",
                                                                "Norja",
                                                                "Viro",
                                                                "Venäjä",
                                                                "Tanska",
                                                                "Latvia",
                                                                "Liettua"), "red", "black")) +
  geom_smooth(method = "lm") +
  geom_text_repel(aes(demokratia_indeksi_vdem,
                      oljy_litrahinta_usd,
                      label = nimi_suom)) +
  theme(plot.caption = element_text(size = 13,
    hjust = 0), axis.title = element_text(size = 15),
    plot.title = element_text(size = 19)) +
  labs(title = "Bensiinin litrahinta vs. demokratia", 
       x = "Demokratia-indeksi (V-Dem) v. 2020", 
       y = "Bensiinin litrahinta, yhdysvaltain dollaria ($) v. 2021",
       caption = "Lähteet: Statistics Times (bensiinin hinta), Varieties of Democracy (demokratia-indeksi)\nKuva: Eemil Mitikka")

```

# Korona-data

```{r}

```

